steps:
# Build all three service images
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-east4-docker.pkg.dev/miso-final-1234/miso-factory/orchestrator:latest', './orchestrator']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-east4-docker.pkg.dev/miso-final-1234/miso-factory/python-agent:latest', './python-agent']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-east4-docker.pkg.dev/miso-final-1234/miso-factory/frontend:latest', './frontend']

# Push all images to the registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east4-docker.pkg.dev/miso-final-1234/miso-factory/orchestrator:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east4-docker.pkg.dev/miso-final-1234/miso-factory/python-agent:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east4-docker.pkg.dev/miso-final-1234/miso-factory/frontend:latest']

options:
  logging: CLOUD_LOGGING_ONLY
