steps:
# Build and push all service images
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-east4-docker.pkg.dev/miso-final-1234/miso-factory/orchestrator:latest', './orchestrator']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-east4-docker.pkg.dev/miso-final-1234/miso-factory/python-agent:latest', './python-agent']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-east4-docker.pkg.dev/miso-final-1234/miso-factory/frontend:latest', './frontend']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east4-docker.pkg.dev/miso-final-1234/miso-factory/orchestrator:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east4-docker.pkg.dev/miso-final-1234/miso-factory/python-agent:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east4-docker.pkg.dev/miso-final-1234/miso-factory/frontend:latest']

# --- ADD THIS NEW STEP ---
# Copy the deployment script to the VM
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'compute'
  - 'scp'
  - 'deploy-miso.sh'
  - 'miso-final-vm:~/deploy-miso.sh'
  - '--zone=us-east4-c'
# --- END NEW STEP ---

# Deploy by running the script on the VM
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'compute'
  - 'ssh'
  - 'miso-final-vm'
  - '--zone=us-east4-c'
  - '--command=bash deploy-miso.sh'

options:
  logging: CLOUD_LOGGING_ONLY
