steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'us-east4-docker.pkg.dev/$PROJECT_ID/miso-factory/orchestrator:v0.1',
    '-t', 'us-east4-docker.pkg.dev/$PROJECT_ID/miso-factory/orchestrator:latest',
    '.'
  ]

images:
- 'us-east4-docker.pkg.dev/$PROJECT_ID/miso-factory/orchestrator:v0.1'
- 'us-east4-docker.pkg.dev/$PROJECT_ID/miso-factory/orchestrator:latest'

options:
  logging: CLOUD_LOGGING_ONLY
