steps:
# Build and push steps (unchanged)
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-east4-docker.pkg.dev/miso-final-1234/miso-factory/orchestrator:latest', './orchestrator']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-east4-docker.pkg.dev/miso-final-1234/miso-factory/python-agent:latest', './python-agent']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-east4-docker.pkg.dev/miso-final-1234/miso-factory/frontend:latest', './frontend']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east4-docker.pkg.dev/miso-final-1234/miso-factory/orchestrator:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east4-docker.pkg.dev/miso-final-1234/miso-factory/python-agent:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east4-docker.pkg.dev/miso-final-1234/miso-factory/frontend:latest']

# Step A: Remotely authenticate Docker on the VM as the default user
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'ssh', 'miso-final-vm', '--zone=us-east4-c', '--command=docker-credential-gcr configure-docker --registries=us-east4-docker.pkg.dev']

# Step B: Copy the deployment script to the VM
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'scp', 'deploy-miso.sh', 'miso-final-vm:~/deploy-miso.sh', '--zone=us-east4-c']

# Step C: Run the deployment script on the VM
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'ssh', 'miso-final-vm', '--zone=us-east4-c', '--command=bash deploy-miso.sh']

options:
  logging: CLOUD_LOGGING_ONLY
