steps:
# (All build and push steps remain the same)
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east4-docker.pkg.dev/miso-final-1234/miso-factory/frontend:latest']

# --- MODIFIED STEP ---
# Copy the deployment script to the VM's temporary directory
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'compute'
  - 'scp'
  - 'deploy-miso.sh'
  - 'miso-final-vm:/tmp/deploy-miso.sh'
  - '--zone=us-east4-c'

# --- MODIFIED STEP ---
# Deploy by running the script from /tmp
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'compute'
  - 'ssh'
  - 'miso-final-vm'
  - '--zone=us-east4-c'
  - '--command=bash /tmp/deploy-miso.sh'

options:
  logging: CLOUD_LOGGING_ONLY
