steps:
# Build and push images
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-east4-docker.pkg.dev/miso-final-1234/miso-factory/orchestrator:latest', './orchestrator']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-east4-docker.pkg.dev/miso-final-1234/miso-factory/python-agent:latest', './python-agent']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-east4-docker.pkg.dev/miso-final-1234/miso-factory/frontend:latest', './frontend']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east4-docker.pkg.dev/miso-final-1234/miso-factory/orchestrator:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east4-docker.pkg.dev/miso-final-1234/miso-factory/python-agent:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east4-docker.pkg.dev/miso-final-1234/miso-factory/frontend:latest']

# Authenticate and pull images on the remote VM
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'ssh', 'miso-vm', '--zone=us-east4-c', '--command=sudo docker-credential-gcr configure-docker --registries=us-east4-docker.pkg.dev']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'ssh', 'miso-vm', '--zone=us-east4-c', '--command=sudo docker pull us-east4-docker.pkg.dev/miso-final-1234/miso-factory/orchestrator:latest']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'ssh', 'miso-vm', '--zone=us-east4-c', '--command=sudo docker pull us-east4-docker.pkg.dev/miso-final-1234/miso-factory/python-agent:latest']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'ssh', 'miso-vm', '--zone=us-east4-c', '--command=sudo docker pull us-east4-docker.pkg.dev/miso-final-1234/miso-factory/frontend:latest']

# Copy and run the deployment script
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'scp', 'deploy-miso.sh', 'miso-vm:~/deploy-miso.sh', '--zone=us-east4-c']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'ssh', 'miso-vm', '--zone=us-east4-c', '--command=bash deploy-miso.sh']

options:
  logging: CLOUD_LOGGING_ONLY
