services:
  app:
    build:
      context: ./python_agent_runner
      dockerfile: Dockerfile
    container_name: miso_app_container
    environment:
      - OLLAMA_HOST=host.docker.internal

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: miso_nginx_container
    ports:
      - "80:80"
    depends_on:
      - app
