services:
  app:
    build:
      context: ./python_agent_runner
    expose: ["5000"]
    volumes: ["./python_agent_runner:/app"]
    command: gunicorn --workers 3 --bind 0.0.0.0:5000 app:app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    depends_on:
      - ollama
  nginx:
    build: ./nginx
    ports: ["80:80", "443:443"]
    volumes: ["./nginx/nginx.conf:/etc/nginx/nginx.conf", "./certbot/conf:/etc/letsencrypt", "./certbot/www:/var/www/certbot"]
    depends_on:
      - app
  certbot:
    image: certbot/certbot
    volumes: ["./certbot/conf:/etc/letsencrypt", "./certbot/www:/var/www/certbot"]
  ollama:
    image: ollama/ollama
    volumes: ["./ollama_data:/root/.ollama"]
    ports: ["11434:11434"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
