version: '3.8'

services:
  miso_app:
    build:
      context: .
      dockerfile: python_agent_runner/Dockerfile
    container_name: miso_app_container
    ports:
      - ""8000:8000""
    volumes:
      - ./python_agent_runner:/app
      - ./research_subjects:/app/research_subjects
      - ./generated_projects:/app/generated_projects
    environment:
      - FLASK_ENV=development
    networks:
      - miso_network

  nginx:
    build:
      context: .  # Corrected: Build context is the project root
      dockerfile: nginx/Dockerfile # Specify the Dockerfile location
    container_name: nginx_proxy
    ports:
      - ""8088:80""
    networks:
      - miso_network
    depends_on:
      - miso_app

networks:
  miso_network:
    driver: bridge
