# Defines the services that make up the MISO application stack.
services:
  # The core MISO application service.
  miso_app:
    build:
      context: .
      dockerfile: ./python_agent_runner/Dockerfile
    container_name: miso_app_container
    ports:
      - '8000:8000'
    volumes:
      - ./python_agent_runner:/app
      - ./research_subjects:/app/research_subjects
      - ./generated_projects:/app/generated_projects
    environment:
      - FLASK_ENV=development
    networks:
      - miso_network

  # The Nginx reverse proxy service.
  nginx:
    build:
      context: ./nginx
    container_name: nginx_proxy
    ports:
      - '8088:80'
    networks:
      - miso_network
    depends_on:
      - miso_app

# Defines the network for communication between services.
networks:
  miso_network:
    driver: bridge
