services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./miso_data.db:/app/miso_data.db
      - ./generated_projects:/app/generated_projects
    environment:
      - SQS_QUEUE_URL=

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - "5173:80"
    depends_on:
      - api
