# agents/ux_design_agent.py

class UX_Design_Agent:
    """
    A specialist "Execution" agent responsible for generating
    UI/UX mockups, wireframes, and component designs.
    """
    def __init__(self):
        print("UX_Design_Agent initialized.")

    def create_component_mockup(self, component_name: str) -> str:
        """
        Generates an HTML mockup for a given UI component.
        
        Args:
            component_name: The name of the component to design (e.g., 'login page').
            
        Returns:
            A string containing HTML representing the component mockup.
        """
        print(f"UX_Design_Agent is creating a mockup for: '{component_name}'")
        
        if "login page" in component_name.lower():
            # This is the "work" product of the agent.
            # In the future, this could be generated by an LLM.
            return """
            <h3>Login Component Mockup</h3>
            <div class="mockup-container">
              <label for="email">Email:</label>
              <input type="text" id="email" placeholder="user@example.com" disabled />
              <label for="password">Password:</label>
              <input type="password" id="password" disabled />
              <button disabled>Sign In</button>
              <a href="#" style="display: block; text-align: center; margin-top: 10px;">Forgot Password?</a>
            </div>
            """
        else:
            return f""
