name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigate to the project directory
            cd ~/miso-factory-repo

            # Clean up Docker to free disk space from previous failed builds
            echo "Pruning Docker system to free up disk space..."
            sudo docker system prune -af

            # Force the server's code to match the repo exactly
            git fetch --all
            git reset --hard origin/main

            # Ensure large model data is removed before the build
            echo "Removing large model data to prevent build failure..."
            rm -rf python_agent_runner/ollama_data

            # Stop any conflicting host-level services
            sudo systemctl stop nginx || true
            sudo systemctl disable nginx || true

            # Run the application stack
            echo "Starting Docker Compose build..."
            sudo /usr/local/bin/docker-compose up --build -d
